/**
 * Supabase Database Types
 *
 * NOTE:
 * This file is normally generated by `supabase gen types typescript`.
 * It was previously overwritten with a shell error string, which breaks TypeScript compilation.
 *
 * Until types are re-generated from the live schema, we provide a safe fallback
 * shape that keeps the app compiling while preserving the `Database` generic
 * expected by `@supabase/supabase-js` and `@supabase/ssr`.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

/**
 * Temporary fallback type.
 *
 * The generated Supabase types were overwritten and are currently unavailable in this
 * workspace environment. Using `any` prevents the Supabase client from collapsing
 * schema types to `never` (which breaks compilation across the app).
 *
 * Regenerate this file with:
 * `supabase gen types typescript --local > src/types/database.ts`
 */
export type Database = any
